### ISSUE TITLE
On Windows execution failed

### ISSUE THREAD

**Issue by SilurianYang** [google/zx#28]
## Expected Behavior
success

## Actual Behavior
```js
Administrator@WIN-JH5VDQS6BP7 MINGW64 /f/codeTest/jsToSh/src
$ zx file:///F:/codeTest/jsToSh/src/index.js
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'f:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at Loader.import (internal/modules/esm/loader.js:165:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at file:///C:/Users/Administrator/AppData/Roaming/npm/node_modules/zx/zx.mjs:51:18
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Administrator@WIN-JH5VDQS6BP7 MINGW64 /f/codeTest/jsToSh/src
$ zx ./index.js
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'f:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at Loader.import (internal/modules/esm/loader.js:165:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at file:///C:/Users/Administrator/AppData/Roaming/npm/node_modules/zx/zx.mjs:51:18
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

```

## Steps to Reproduce the Problem

1. `touch index.js`
2. `vim index.js`
```js
#!/usr/bin/env zx

void (async function () {
	let count = parseInt(await $`ls -1 | wc -l`);
	console.log(`Files count: ${count}`);
})();
```
3.` ./index.js` or `zx ./index.js` or  `zx file:///F:/codeTest/jsToSh/src/index.js`

## Specifications

* node: v14.16.0

* Platform: Windows 10 Professional

**Comment by Artoria2e5** [comment]
I think #22 is supposed to fix this.

**Comment by SilurianYang** [comment]
@Artoria2e5  I try

**Comment by SilurianYang** [comment]
> I think #22 is supposed to fix this.
 Succeeded

**Comment by antonmedv** [comment]
Done.

**Comment by Artoria2e5** [comment]
I don't think it's done. The offending `path = join(process.cwd(), firstArg)` code is still present and messing with Windows.

**Comment by antonmedv** [comment]
#45

**Comment by MarkosKon** [comment]
> I don't think it's done. The offending `path = join(process.cwd(), firstArg)` code is still present and messing with Windows.

It would break something if that line changed to `path = resolve(firstArg)`? 

My problem was different, though. I was trying to execute a zx file from path (on Windows with Git bash), and this change solved it.

**Comment by antonmedv** [comment]
Awesome. Lets create pr with it. And test if possible.

**Comment by MarkosKon** [comment]
> Awesome. Lets create pr with it. And test if possible.

I can make the above change and write a test that executes a new script from the PATH variable if you want. 

The problem is that zx on Linux can already execute a script from PATH, from what I see. The test may also pass on my local Windows machine, but how do we write a test that succeeds on Windows with Git bash (with GitHub actions)?
